// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdfovqfvisrtzdtkgcdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkZm92cWZ2aXNydHpkdGtnY2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzQ1ODIsImV4cCI6MjA2NTk1MDU4Mn0.an5CvVlhuaio_OShrEvBuNkbzaFxz5huuiQxdArfIPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);